### ISSUE TITLE
Now Deployment

### ISSUE THREAD

**Issue by stunjiturner** [sveltejs/sapper-template#102]
When I attempt to deploy to the Now 2.0 nerveless, it does not produce a working app, just shows the file system of the app in web browser,

**Comment by antony** [comment]
I've been considering this myself. I think we need to fork https://www.npmjs.com/package/@now/next in order to get it to work.

**Comment by stunjiturner** [comment]
I am uptown to task, with some pointers in the right direction.

**Comment by antony** [comment]
@stunjiturner you would be a legend.

It appears to me that the structure of a next app is very similar to a sapper app, so I would just recommend taking a copy of the next builder from https://github.com/zeit/now-builders and adjusting the way that routes are mounted (at the bottom of the launcher.js file I believe).

I am also aware that there might be a function in the 'now' cli to run a local `now.sh` emulator to make testing this a bit easier.

Happy to help where I can!

**Comment by stunjiturner** [comment]
When sapper builds a production bundle, is creates a bundle.js file and index.html in the /dist folder?

**Comment by antony** [comment]
To be honest, I'm not sure of the exact format.

I'd recommend checking out the template and simply running `npm run build` to inspect.

**Comment by stunjiturner** [comment]
I noticed that the realworld app in the svelte root repo, uses now for deployment?

**Comment by antony** [comment]
@stunjiturner yeah - now v1, it's a different beast to what now is becoming, hence the need for support. Once they deprecate v1, the app will no longer work.

**Comment by bob-bea-fre** [comment]
Just add a now.json with:
`{
  "version": 1
}`

**Comment by antony** [comment]
@bob-bea-fre yes, but this isn't future proof. Now is moving on, and Sapper should follow it.

**Comment by WHenderson** [comment]
Just wondering if anyone was working on this at the moment. I'm evaluating options so it would be great to test this out.

**Comment by antony** [comment]
@WHenderson yeah, @thgh has done it here: https://github.com/sveltejs/sapper/issues/564

I'm currently using it for a project, seems to work well!

**Comment by danielschmitz** [comment]
Hi, im building a "sapper+bulma crud"

my now v2 implementation is here: [diff](https://github.com/danielschmitz/svelte-sapper-bulma-crud/commit/331e5f59fe8e9ca70c051f338ae77b277214790c) [demo](https://svelte-sapper-bulma-crud.danielschmitz.now.sh/home)

**Comment by vladejs** [comment]
We should be able to create a now v2 deployment by exporting every route as an independent lambda, like next.js does. 

Having build/index.js entry point means a single point of failure

**Comment by kaleidawave** [comment]
I think until this is better documented and on v2 we should remove the now part from the documentation. It is dangerous if it uploads and exposes all working files as it could expose server secrets which lie in the sapper app
