### ISSUE TITLE
Error when using on Mac OS High Sierra

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper-template#114]
```
degit sveltejs/sapper-template#webpack 0.25.0
cd 0.25.0
yarn
yarn dev
```

It throws this error:
> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: custom keyword definition is invalid: data/errors should be boolean

**Comment by thgh** [comment]
I think this is webpack related: https://github.com/webpack/webpack/issues/8768

**Comment by Conduitry** [comment]
Yeah this looks like an issue with a dependency of webpack. It also looks like a new version of that dependency (`ajv`) has been released, fixing the bug.
