### ISSUE TITLE
Not clear how to use this project any more

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper-template#121]
I'm starting a new Sapper project after a while, and I geneally `degit` this, `npm i` and `npm run dev`, as per readme.

Turns out that this no longer works, I'm assuming due to the support of rollup and sapper, and there is no `package.json`, only a `package-json.template`. If you rename and try to `npm i` this also doesn't work.

The problem is, this template has some blocks I don't recognise in it, such as a `merge-configs` block, and there doesn't appear to be any documentation regarding what this is, or how to use it.

Any chance the readme could get an update so that this project is usable for newcomers (and oldcomers like me!) again?

**Comment by antony** [comment]
Aaand I just spotted the #branches - in the readme. Ignore most of this issue.

What might be useful though is clearer instructions. It's easy not to spot the branch markers and then try to checkout master and run it directly.

Closing :)

**Comment by lunchboxer** [comment]
Have a closer look. You've got to pick either the roll up branch or the webpack branch
