### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by Sh1d0w** [sveltejs/sapper-template#126]
The current repo uses Svelte 2, having some problems with running the project if I manually update the dependency to Svelte 3 which is the latest.

**Comment by jarrodldavis** [comment]
Try using either of these branches instead:

https://github.com/sveltejs/sapper-template/tree/rollup-v3
```sh
$ npx degit sveltejs/sapper-template#rollup-v3
```

https://github.com/sveltejs/sapper-template/tree/webpack-v3

```sh
$ npx degit sveltejs/sapper-template#webpack-v3
```

**Comment by Sh1d0w** [comment]
Thanks!
