### ISSUE TITLE
Hot reloading is showing a directory listing - 0.27.1

### ISSUE THREAD

**Issue by jcollum-nike** [sveltejs/sapper-template#142]
`npx degit sveltejs/sapper-template#rollup first-sample`

` npm install `

`npm run dev` 

All fine but when I make a change to `src/routes/index.svelte` as suggested it reloads a directory listing. 

![image](https://user-images.githubusercontent.com/40277227/58141026-a4e2a980-7bf6-11e9-9be7-ae18986deb88.png)

**Comment by Conduitry** [comment]
I can't reproduce this. The only thing out of the ordinary I see is that you're hosting on port 3001. The default is 3000 - Do you already have another server running? I also can't tell what directory it is that's being served there. It doesn't look like any of the directories related to this Sapper app.

**Comment by jcollum-nike** [comment]
Just following the instructions on the screen. I have a different app running on 3000. 

```
✗ npm run dev

> TODO@0.0.1 dev /Users/jcol53/Documents/work/sapper/first-sample
> sapper dev

✔ server (760ms)
✔ client (762ms)
> Listening on http://localhost:3001
✔ service worker (20ms)
```

**Comment by Conduitry** [comment]
I'm not able to reproduce this. If I have something already running on 3000, then running `npm run dev` on a new sapper-template clone gives me the app running on 3001. When I edit `src/routes/index.svelte`, the app live reloads as expected. I'm on Chrome.

Can you tell what directory it is that you're seeing the directory listing of?

**Comment by jcollum-nike** [comment]
OK here you go 

If I had to guess what directory that is I'd say it's the multipart js that svelte creates for serving up pages? 

![sapper bug](https://user-images.githubusercontent.com/40277227/58215184-7b388980-7cad-11e9-9fd5-05b600727e36.gif)

**Comment by Conduitry** [comment]
On the off chance that this is something you're still seeing, this is still something that I don't think anyone else was able to reproduce. It certainly looks like a bizarre environmental thing, or like you had something else already serving on port 3000 - and in either case, an issue on this repo isn't the right place to get help with that.
