### ISSUE TITLE
Suppress circular reference warnings from Rollup

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper-template#145]
For everyone's sanity, I think it would be best if rollup.config.js had an `onwarn` which suppressed the circular dependency warnings from Sapper, and ideally left other circular warnings intact. This can be removed once stuff in Sapper is reorganized to avoid this.

**Comment by thgh** [comment]
Nice! Perhaps refine the check that it only suppresses circular dependencies involing `@sapper`:
```
function onwarn(warning, warn) {
	if (
		warning.code === 'CIRCULAR_DEPENDENCY' &&
		warning.importer.includes('src/node_modules/@sapper/')
	) {
		return
	}
	warn(warning)
}
```
