### ISSUE TITLE
Service worker throws errors on other apps using localhost

### ISSUE THREAD

**Issue by 1wheel** [sveltejs/sapper-template#16]
Killing the`npm run dev` process, running `npx hot-server` and opening the dev tools shows a ton of errors:

![image](https://user-images.githubusercontent.com/1643998/34348233-4085caf6-e9d7-11e7-8b5e-310c97f8bb80.png)

Not sure if there's a way to automatically uninstall the service worker (unlikey) or limit it to `localhost:PORT`.

**Comment by Rich-Harris** [comment]
This ought to be fixed now, as Sapper will start a separate dev server for HMR stuff. So I'll close this
