### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by GottZ** [sveltejs/sapper-template#160]
hey there. i know how much of a pain it can be to have inconsistencies in projects when multiple people work on one project.

there is a neat little tool i'd suggest adding as default into the template:
https://editorconfig.org/

example: https://github.com/emberjs/ember.js/blob/master/.editorconfig
another example: https://github.com/help-appreciated/svelte-smart-complete/blob/master/.editorconfig

i did not create a pull request yet because i think this requires some discussion and 👍 beforehand.

**Comment by silentworks** [comment]
I think this should be something a team working on a project decides to add and not the framework supplying one. Some teams don't use editorconfig, some teams rely on prettier instead along with eslint. So adding this in wouldn't be of much benefit to such teams.

**Comment by NetOperatorWibby** [comment]
I agree with @silentworks, I'd just replace the included file with my own.

**Comment by donnisnoni95** [comment]
@GottZ  Ahh .. that's a bad idea, Agree eith @silentworks... 

This is a template ... meaning this template must be universal, not specific. Let them decide later what style of coding they like.

Just a suggestion: You fork this repo then add what you want, then use degit to generate your repo as your sapper template.

**Comment by donnisnoni95** [comment]
@Conduitry close this

**Comment by GottZ** [comment]
okidoki. reasonable.
