### ISSUE TITLE
Question: how to generate a dynamic static files for export

### ISSUE THREAD

**Issue by bartveneman** [sveltejs/sapper-template#163]
- Sapper: 0.27.4
- OS: MacOS 10.14.6
- Node: 10.16.0
- NPM: 6.10.2

How would I go about generating static files like a sitemap.xml or RSS feed.xml? I'm particularly interested in the export function. I got it working for the `sapper dev` command, but it doesn't work for `sapper export`. Here's what I tried (with a couple different variations in filenames and such):

`src/routes/feed.xml.js`
```js
import posts from "./blog/_posts.js";

const feed = `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
  <title>...</title>
  <description>...</description>
  <link>...</link>
  ${posts
    .map(post => {
      return `
        <item>
          <title>${post.title}</title>
          <description>...</description>
          <link>...</link>
          <pubDate>...</pubDate>
        </item>
      `;
    })
    .join("")}
</channel>
</rss>`;

export function get(req, res) {
  res.writeHead(200, {
    "Content-Type": "application/rss+xml"
  });
  res.end(feed);
}
```

When running `sapper dev` this shows up for `http://localhost:3000/feed.xml`, but it does not get exported with `sapper export`.

**Comment by Conduitry** [comment]
Exports work by crawling the site starting at the root and following all hyperlinks, and if you don't have a link to your sitemap.xml from anywhere, it won't be included.

Just yesterday, `sapper export` go an `--entry` option added that lets you specify multiple points to start crawling at, which you could use here if you don't want to add a link to the file.

**Comment by bartveneman** [comment]
Oooh, I found the entry option in the source code, but I’ll probably need to updat my Sapper version to make that work! 😁

**Comment by bartveneman** [comment]
Checked, and can verify that linking the URL in another template does the trick. A simple `<a href="/feed">RSS Feed</a>`. 

Sapper keeps amazing me 😍
