### ISSUE TITLE
process.binding is deprecated

### ISSUE THREAD

**Issue by NetOperatorWibby** [sveltejs/sapper-template#164]
[The line in question](https://github.com/sveltejs/sapper-template/blob/master/rollup.config.js#L80):

```js
require('module').builtinModules || Object.keys(process.binding('natives'))
```

ESLint complained about it so I removed ` || Object.keys(process.binding('natives'))`. App is working perfectly fine without it, in development (too soon for production). I'm on Node 12, if that helps.

**Comment by MaxMilton** [comment]
It's to support node versions earlier than `v9.3.0`. If you're using an up-to-date version of node it's safe to remove.

See <https://nodejs.org/api/modules.html#modules_module_builtinmodules>.

**Comment by NetOperatorWibby** [comment]
Oh that's wonderful, I'll just close this then.
