### ISSUE TITLE
Applying style to body tag without using global.

### ISSUE THREAD

**Issue by jaybeemind** [sveltejs/sapper-template#168]
Hi, I have a simple problem where I need to add styles to the body tag on one page.
Has anyone ever experienced this?
Using global on one page also applies style to other pages even though it was only loaded on one page (not _layout).

**Comment by thgh** [comment]
I would use this:

```js
onMount(() => {
  document.body.classList.add('some-class')
  return () => document.body.classList.remove('some-class')
})
```

or

```html
<svelte:head>
  <style>body{}</style>
</svelte:head>
```

**Comment by sw-yx** [comment]
oh that second solution is smart!
