### ISSUE TITLE
Post caching best practices

### ISSUE THREAD

**Issue by 1wheel** [sveltejs/sapper-template#17]
Might be out of scope, but should caching be on by default? 

https://github.com/sveltejs/sapper-template/blob/master/routes/api/blog/index.js#L13

If you reload the page with an unexpired cache after there's been a new post, it'll show up for a split second as part of the static html before getting deleted when the page hydrates.

**Comment by Rich-Harris** [comment]
Good point. I always get caching stuff wrong. Probably better to just remove them
