### ISSUE TITLE
npm run dev is fine, but npm run build fails on windows (7)

### ISSUE THREAD

**Issue by tomcon** [sveltejs/sapper-template#18]
ERROR in ./routes/index.html
Module not found: Error: Can't resolve 'C:Users c7AppDataLocalTemp/svelte-1190322880.css' in 'C:\Apps\Testarea\svelte\sapper\my-app\routes'
 @ ./routes/index.html 158:0-64
 @ ./templates/.main.rendered.js

..... 
.....

**Comment by Rich-Harris** [comment]
This *might* have been fixed by https://github.com/sveltejs/svelte-loader/pull/36 — could you try updating `svelte-loader` please?

**Comment by tomcon** [comment]
Re-installed and looking good now @Rich-Harris :+1:

**Comment by Rich-Harris** [comment]
excellent! closing
