### ISSUE TITLE
Can we change the Borat picture?

### ISSUE THREAD

**Issue by amedeedaboville** [sveltejs/sapper-template#185]
Hi, I just started with Svelte & Sapper, love the concepts, and it's been really nice to use Svelte so far.

At first I thought the sample's borat image was funny, but the more time passed, the more it left a bad taste in my mouth. The borat quotes I remember are all gross.

I don't think it puts this framework on a good first foot with beginners to have that image there.
There are a million other fun images to put there to make a better first impression.

eg an alternative is the [Success Kid Meme](https://imgflip.com/memegenerator/Success-Kid)

here's one https://i.imgflip.com/3j2nq8.jpg

**Comment by hangtwenty** [comment]
**Agree!**

I get the intention to put something funny and recognizable on the homepage, but a lot of people find that movie insensitive or unfunny or both. It's comedy, sure, but I think it's pretty clear why it's controversial, so it's just... not really relevant to this project.

**Comment by arxpoetica** [comment]
The nice thing about this template is one can immediately change it after `degit`-ing it.

I always replace it with this:

![image](https://user-images.githubusercontent.com/111424/74090659-27ecae00-4a6b-11ea-8cfc-36a40083e05a.png)

**Comment by amedeedaboville** [comment]
Yes you can change it, but defaults matter. Borat is not a good first impression for Sapper.

This Borat default +closing the issue makes me feel bad, so I won't be using Sapper. I'm saying this because I think it will happen to other people too, and I wanted to help you not alienate more people in the future.

**Comment by pngwn** [comment]
This issue shouldn't have been closed.

We certainly don't want to alienate anyone and it would silly of us to lose users over this when the fix is so simple.

I think it's pretty clear that many people find Borat offensive, or just in poor taste, swapping it out is a no brainer.

**Comment by pngwn** [comment]
If someone wants to prepare a PR to make this change, we can take a look at it.

**Comment by artemjackson** [comment]
The issue where REAL problems are discussed
\*facepalm\*

**Comment by Anthropic** [comment]
An obvious reason to change Borat would be copyright infringement wouldn't it?

Ironically I find children more offensive in a time of dire global overpopulation than Borat, but I digress, why not just put the S from the Svelte & Sapper logos there  (in #8A695A which is the midway color between them) and be avoid demo image as a bikeshedding discussion in future?

Basic logo would be a smaller file size than a pic too.

**Comment by arxpoetica** [comment]
Fixed in https://github.com/sveltejs/sapper-template/pull/200

**Comment by 73DX** [comment]
Too bad. Discarding Svelte as our preferred front-end framework going forward because o
removal of Borat's pic. Those criticizing the use of that image in Svelte, certainly never understood what the movie was all about. Our user base is currentky 150M users who could have benefited from it.

**Comment by pngwn** [comment]
You literally cannot please anyone.
