### ISSUE TITLE
support dev tool

### ISSUE THREAD

**Issue by mehdiraized** [sveltejs/sapper-template#203]
plz support svelte dev tool in chrome

**Comment by MaxMilton** [comment]
Could you elaborate? `Svelte Devtools` already works in both Chrome and Firefox

- https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn
- https://addons.mozilla.org/en-US/firefox/addon/svelte-devtools/
- https://github.com/RedHatter/svelte-devtools

**Comment by mehdiraized** [comment]
### sapper not supported
```To connect to Svelte perform a hard refresh (ctrl+F5) or click here.

Not working? Did you...

- Use Svelte version 3.12.0 or above?

- Build with dev mode enabled?

```



> Could you elaborate? `Svelte Devtools` already works in both Chrome and Firefox
> 
> * https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn
> * https://addons.mozilla.org/en-US/firefox/addon/svelte-devtools/
> * https://github.com/RedHatter/svelte-devtools

**Comment by MaxMilton** [comment]
Yes, Svelte version `3.19.1` in dev mode together with the Chrome plugin works great. You'll need to provide more information if you want help debugging your issue.

To start with, please checkout a clean copy of this repo and see if you can still reproduce the problem.
