### ISSUE TITLE
Use of `process.binding` is deprecated since node v10

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper-template#206]
However the way Sapper uses it means that I'm not 100% sure of the replacement.

In rollup.config.js we use `process.binding('natives')`

I've read about:

1) Not using natives as it is process internal
2) Installing the `natives` module
3) `require`ing from the native `bindings` package.

I suppose what is required here is to understand what we're trying to achieve here to figure out what the replacement should be.

**Comment by Conduitry** [comment]
It's just used as a fallback for `require('module').builtinModules`, which has been available longer than `process.binding` has been deprecated, so I don't think that's a concern.

If we drop support for Node 8 in the template (which we'd have to do to upgrade to Rollup 2), then we could also remove this.

**Comment by Conduitry** [comment]
Resolved by #239.
