### ISSUE TITLE
Question: Deployement

### ISSUE THREAD

**Issue by Ebeldev** [sveltejs/sapper-template#209]
Hi, 

I was looking to find some information on how to deploy a sapper application on a server like Digital Ocean and not Now, or Heroku or Netlify.

Is there any documentation on the process to serve a sapper application that is hosted on linux server?

Yours,

**Comment by antony** [comment]
Hi Ebeldev. We have a deployment section in the Sapper docs, but it has some open PRs which require merging. I'll have a look at them later today.

Depending on your application type, copy the __sapper__/build or __sapper__/export directory along with the `static` directory to your server, and run:

node __sapper__/build

or serve up __sapper__/export as a simple public directory.

**Comment by Ebeldev** [comment]
Hi @antony Thank you for your response. 
I already have on my server in my public_html folder my project. I ran npm run build. Then I have pm2 that runs npm run start. which is "node __sapper__/build".

On my local machine the build runs perfectly. 

On my server, I get a 503 error. 

And on the server the logs gives me this. 

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:5)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
/home/../../public_html/__sapper__/build/template.html:1
<!doctype html> <html lang=en> <head> <meta charset=utf-8> <meta content="width=device-width,initial-scale=1" name=viewport> <meta content=#333333 name=theme-color> %sapper.base% <link href=global.css rel=stylesheet> <link href=manifest.json rel=manifest crossorigin=use-credentials> <link href=favicon.png rel=icon type=image/png> <link href="https://fonts.googleapis.com/css?family=Lora:400,500i,600i,700|Quicksand:400,500,700&display=swap" rel=stylesheet> <style>:root{--red:#ff0000;--darkColor:#1d2027;--primary:var(--red);--secondary:var(--darkColor);--grey:#E9E9E9;--darkGrey:#454545;--mainF:'Quicksand',sans-serif;--headerF:'Lora',serif;--ratio:1rem}body{font-family:var(--mainF)}h1,h2,h3,h4,h5,h6{font-family:var(--headerF)}a{text-decoration:none}</style> %sapper.styles% %sapper.head% </head> <body> <div id=sapper>%sapper.html%</div> %sapper.scripts%

**Comment by antony** [comment]
@Ebeldev Github issues isn't the right place for support. We'll update the docs as they clearly lack in this area, but questions regarding your specific deployment issues should be discussed with us at https://svelte.dev/chat where you'll be able to get further help.
