### ISSUE TITLE
Is there a way to use this without webpack?

### ISSUE THREAD

**Issue by NetOperatorWibby** [sveltejs/sapper-template#21]
Sapper looks pretty cool but I'm not keen on adding yet more things to configure to my projects.

**Comment by Rich-Harris** [comment]
Currently, no, though we intend to add support for other bundlers (Rollup and Parcel) when possible. But the idea is that if you use this project template, *you* don't need to configure anything — it's already done for you! The only time you'd need to touch the config files is if you wanted to add some new capability.

**Comment by NetOperatorWibby** [comment]
Hmm, okay. Thanks for the info!
