### ISSUE TITLE
segment property error in _layout

### ISSUE THREAD

**Issue by whakomatic** [sveltejs/sapper-template#210]
I removed nav.svelte
this meant i didnt need the segment in layout anymore.

That causes this console error message:
`<Layout> was created with unknown prop 'segment'`

When I add the property back to _layout.svelte that console error goes away but I now get a compilation warning.
`Layout has unused export property 'segment'. If it is for external reference only, please consider using export const segment`

If i switch to a const the unknown prop error shows up again.

I dont think this the error or warning cause issues, but it would be good to fix one or the other.

**Comment by antony** [comment]
This doesn't relate to the Sapper template - it is under discussion here https://github.com/sveltejs/sapper/issues/824

**Comment by dan-unhuman** [comment]
if you don't need the prop, you can do this

on `_layout.svelte` i use this two line code
```
export let segment;
segment = !segment;
```
