### ISSUE TITLE
Rollup variant of the sapper template is broken since @rollup/plugin-commonjs@11.1.0 was released

### ISSUE THREAD

**Issue by bryanwood** [sveltejs/sapper-template#211]
A fresh `degit` of the template since `@rollup/plugin-commonjs@11.1.0` was released results in the following:

```
C:\projects>npx degit sveltejs/sapper-template#rollup my-app
>> cd my-app
>> npm install
>> npm run dev
npx: installed 1 in 1.297s
> cloned sveltejs/sapper-template#rollup to my-app
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN TODO@0.0.1 No repository field.
npm WARN TODO@0.0.1 No license field.

added 271 packages from 199 contributors and audited 2224 packages in 6.095s

19 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> TODO@0.0.1 dev C:\projects\my-app
> sapper dev

✗ client
'import' and 'export' may only appear at the top level
11: }
12:
13: export function connect(port) {
    ^
14:   if (source || !window.EventSource) return;
✔ server (806ms)
✔ service worker (189ms)
> Listening on http://localhost:3001
```

Pinning `@rollup/plugin-commonjs` to `11.0.2` resolves it.

Possibly relevant commits from `@rollup/plugin-commonjs`:
- https://github.com/rollup/plugins/commit/04138d6505ce9a4bc602ad35737d79701fc1b698
- https://github.com/rollup/plugins/commit/cbc341d07cc1343ee03ada5d268b8f2ee4778c63
- https://github.com/rollup/plugins/commit/a66c8c70fc18f3967783b4e3e16e0aecd437d1f1
- https://github.com/rollup/plugins/commit/b6621262e284057e5740089388ffdcc6c391998d
- https://github.com/rollup/plugins/commit/4207609dafb4523233870f4ca79770f992e6a20b

**Comment by Conduitry** [comment]
Closing in favor of https://github.com/sveltejs/sapper/issues/1151 which has more discussion, but it does seem like this is probably something that needs to be fixed in the Rollup plugin.
