### ISSUE TITLE
Live reload not working out of box in roll up template

### ISSUE THREAD

**Issue by stolinski** [sveltejs/sapper-template#212]
I followed the instructions here: 
https://sapper.svelte.dev/docs#Getting_started

and don't have any kind of live reloading working when making changes to any files. Build process is showing changes, no reloading taking place on the client. attempted in Chrome and Brave. Live reloading works on other platforms without issue.

Network tab shows a failed request for http://localhost:3000/client/undefined not sure if these are related.

**Comment by stolinski** [comment]
Seems to be the same issue here: https://github.com/sveltejs/sapper/issues/1151

**Comment by Conduitry** [comment]
Yes, the issue is that no javascript is running at all, because the build fails due to presumably a bug in that Rollup plugin.

**Comment by stolinski** [comment]
JW why this  got closed if it's still a bug.

**Comment by Conduitry** [comment]
Because there's another issue for it.

**Comment by stolinski** [comment]
Sure, but not in regards to the templates. If a fix is a pinned version in then temp, shouldn't that be tracked here until a fix is in?

**Comment by stolinski** [comment]
I create a temp fix for this just to prevent first time users from seeing broken code OOTB.
