### ISSUE TITLE
Cypress missing from devDependencies

### ISSUE THREAD

**Issue by bahmutov** [sveltejs/sapper-template#22]
`npm i -D cypress` should be good enough to fix it ;)

**Comment by bahmutov** [comment]
Oh, I see what you are doing - minimize the install time. Probably just need to document how to run tests then.

**Comment by Rich-Harris** [comment]
Ah, yep. Reason behind this was I was having problems installing Cypress when apps got deployed to Now (which installs devDependencies by default so that it can `npm run build`)

**Comment by bahmutov** [comment]
Oh, I remember this. Ok, I will close it - but it might be a problem if there are multiple dev dependencies to install - they will be duplicated across CI's or maybe could be placed into single `npm run install-dev` command.

**Comment by tomasvts** [comment]
This should be explained in the docs:   
https://sapper.svelte.dev/docs/#Testing

**Comment by rdela** [comment]
Opened https://github.com/sveltejs/sapper/pull/975 with Docs addition suggested by tomasvts.
