### ISSUE TITLE
Could not find commit hash for rollup/webpack

### ISSUE THREAD

**Issue by manvankaliber** [sveltejs/sapper-template#220]
I'm trying to install sapper but i'm getting the following error;

![image](https://user-images.githubusercontent.com/12383587/80732337-7494d200-8b0c-11ea-8244-c6b7bb34dd23.png)

**Comment by sw-yx** [comment]
https://github.com/sveltejs/sapper-template/tree/rollup

https://github.com/sveltejs/sapper-template/tree/webpack

**Comment by UltraCakeBakery** [comment]
I didn't have git installed on its own. I normally use 3th party git tools.
That's why it didn't work.

If someone runs in to this problem, just download git;
https://git-scm.com

**Comment by PursuitStar** [comment]
Maybe the version of Node is too low
