### ISSUE TITLE
change rollup-plugin-babel to @rollup/plugin-babel

### ISSUE THREAD

**Issue by mehdiraized** [sveltejs/sapper-template#225]
hi plz upgrade this package

**Comment by sw-yx** [comment]
lol why

**Comment by Conduitry** [comment]
`@rollup/plugin-babel` is the new official one, and`rollup-plugin-babel` is deprecated. When I quickly tried to upgrade a project to the new version (which is also a new major version with breaking changes), I ran into some Babel helper configuration issues and put it aside for the time being, but this should be revisited soon.

**Comment by richardeschloss** [comment]
Warning that shows when running the command on [sapper home page](https://sapper.svelte.dev/)
"npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel."

Minor edit: the spelling of the issue's title..."rullup --> rollup"

**Comment by mehdiraized** [comment]
https://github.com/sveltejs/sapper-template/pull/221
