### ISSUE TITLE
add sapper into preexisting application

### ISSUE THREAD

**Issue by shreyansh-zazz** [sveltejs/sapper-template#234]
I have a node.js application, though it is a good idea to separate backend and frontend in two different repositories. But for this project I am working on, I would very much like to have both of them in a single repository.

My backend doesn't use `rollup` or `webpack`, but it does use `babel` and `eslint`. Can someone here help me setting it up?

**Comment by antony** [comment]
Hi @shreyansh-zazz - we can't help with support questions here. Please use the [Svelte Discord](https://svelte.dev/chat)
