### ISSUE TITLE
Module not Found

### ISSUE THREAD

**Issue by LaniJW** [sveltejs/sapper-template#236]
I encountered this issue today where I try to compile my project but the server crashes immediately and it says that it can't find one of my modules/routes.  
Something weird I noticed, was that it generated some weird code into the server.js file of a __sapper__ compilation: `var umlaut$1 = require('src/routes/x/umlaut');`

Let me know what other information I can provide you with.

**Comment by antony** [comment]
it looks like you have non-latin characters in your routes.

The information we would need is a reproduction project, i.e. one with your non-latin characters in it.

**Comment by LaniJW** [comment]
I would rather not publicize the project. Can I somehow send this to you privately?

**Comment by antony** [comment]
Simply create a small, simple reproduction of the issue. I don't need your entire project.

**Comment by LaniJW** [comment]
I wouldn't even know how to do that. I wasn't able to find a non-latin character anywhere in the routes.

**Comment by antony** [comment]
you `npx degit` the Sapper template, and you try to recreate the offending code in it.

I can see from your original issue that you have an umlaut somewhere in your code. Try searching for the umlaut, or using the generated server.js to give you an idea of where the umlaut occurs.

**Comment by LaniJW** [comment]
I'm sorry but I'm not able to recreate the issue. My original project never had an umlaut in its routes. I even recreated all the files in that directory and the build still seemed broken. Now everything seems to be working fine.
