### ISSUE TITLE
package.json not having "dependencies" causes unfriendly error

### ISSUE THREAD

**Issue by tv42** [sveltejs/sapper-template#250]
I was just experimenting with a from-scratch project that was mostly intended to generate static files for SPA use.
My package.json had no `dependencies` key, just `devDependencies`. The file had been reached with `yarn init` and `yarn add --dev`, and not by manual editing, so that sounds likely a valid and even likely scenario.

Anyway, not having `dependencies` causes this very unhelpful error. The line number does not match, I found the actual cause mostly by looking for calls to `keys`.

```
$ sapper dev -p 5000
(node:28) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/src/rollup.config.js:81:22)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.require.extensions..js (/src/node_modules/sapper/dist/create_manifest_data.js:930:12)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Function.load_config (/src/node_modules/sapper/dist/create_manifest_data.js:936:18)
    at async Object.create_compilers (/src/node_modules/sapper/dist/create_manifest_data.js:1204:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The fix is pretty simple:

```
-    external: Object.keys(pkg.dependencies).concat(
+    external: Object.keys(pkg.dependencies || {}).concat(
```

**Comment by tv42** [comment]
Maybe this value for `external` (and `onwarn` while we're at it) should come from

```
import config from "sapper/config/rollup.js"
```

Even better, `sapper dev` etc when calling roundup could provide good defaults -- it's not like a sapper project's `rollup.config.js` would really be valid to feed directly to rollup, anyway, with the `client`/`server`/`serviceworker` top-level exports.

**Comment by benmccann** [comment]
Thanks for taking the time to write up your experience

Ultimately, I'm not sure the proposed changes are ones we'd want to make. E.g. I'm not sure we should make the userland code more complicated to deal with scenarios where people copy part and not others leaving their project in a broken state. There's no valid project that has no `dependencies`, so I'm not really sure it's worth it the extra code for everyone else. There's nearly an infinite number of ways you could setup your project wrong. E.g. what if you don't have a `package.json` at all? I think things would still break in that case

We actually are somewhat considering or even working on making the `rollup.config.js` be able to fed directly into Rollup, so I don't think we'd want to go in the other direction by taking configuration out of the `rollup.config.js`

**Comment by Conduitry** [comment]
I think I'm with @benmccann on this one. This is intended as a Sapper template - not as an SPA template - and we don't want to be catering to uses outside that.
