### ISSUE TITLE
Add typescript support to template

### ISSUE THREAD

**Issue by martonlederer** [sveltejs/sapper-template#251]
[This](https://svelte.dev/blog/svelte-and-typescript#What_about_TypeScript_in_Sapper_projects) blog post says, that typescript is now supported by Sapper. It would be great if this template contained a similar file to the Svelte template's [`scripts/setupTypeScript.js`](https://github.com/sveltejs/template/blob/master/scripts/setupTypeScript.js), since [this guide](https://svelte.dev/blog/svelte-and-typescript#Adding_TypeScript_to_an_existing_project) only works on Svelte projects.

**Comment by TheComputerM** [comment]
I think this is now fixed
