### ISSUE TITLE
How to publish a production site to run in an external HTTP server like Nginx?

### ISSUE THREAD

**Issue by silvioprog** [sveltejs/sapper-template#258]
Hi.

I have been trying to generate a production app (a small marketing site) to use in an external HTTP server like Nginx, but after performing `npm run build`, the directory `__sapper__\build` contains only files to run my application inside NodeJS.

So, is there any command to generate files like `index.html`/`styles.css`/`main.js` etc. to run my site in a real HTTP server (like a hosting server, Nginx, Apache etc.)?

TIA for any help!

**Comment by benmccann** [comment]
https://sapper.svelte.dev/docs#Exporting
