### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 7yearold** [sveltejs/sapper-template#264]
```
sveltejs\sapper-template-rollup\rollup.config.js:1
import resolve from '@rollup/plugin-node-resolve';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by 7yearold** [comment]
This is a bug.

**Comment by 7yearold** [comment]
It occurs when I run `npm run build`

**Comment by pngwn** [comment]
We'll need a reproduction to look into it but if this is occurring it would be a rollup bug.

**Comment by 7yearold** [comment]
Ok, what do you need from my end?

**Comment by antony** [comment]
@7yearold your project, checked in, as a github repository.
If it's just the template, list the steps you did to create it

Also please tell us the version of node and npm/yarn etc you are using

**Comment by 7yearold** [comment]
I used the instructions provided and degit the repository with `npx degit "sveltejs/sapper-template#rollup" my-app` then `npm install` and after that `npm run build` which resulted in the error. I'm using NPM 6.14.8

**Comment by 7yearold** [comment]
Actually, nevermind I'll use a different library.

**Comment by 7yearold** [comment]
Thank you! @antony @pngwn @Conduitry You can close this one.
