### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by nolanlawson** [sveltejs/sapper-template#27]
Using d93604d62270226f22cf6861d7c2451d6e7e5b5e and following the steps from the "getting started" guide:

```
degit sveltejs/sapper-template my-app
cd my-app
npm install
npm run build
npm start
```

Then navigate to `http://localhost:3000/blog/what-is-sapper`.

Result: the page loads fine, but there's an error in the console because one of the modules apparently can't be loaded by webpack:

Stacktrace (with minification turned off):

```
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap b018e58b911432dbd00b:49)
    at Object.11 (svelte-2284459081.css:1)
    at __webpack_require__ (bootstrap b018e58b911432dbd00b:49)
    at Object.10 (svelte-2284459081.css?b9c7:4)
    at __webpack_require__ (bootstrap b018e58b911432dbd00b:49)
    at Object.15 ([slug].html:9)
    at __webpack_require__ (bootstrap b018e58b911432dbd00b:49)
    at <anonymous>
```

Seems it can be traced back to a `require()` in a generated `svelte-***.css` file:

```js
exports = module.exports = require("../../../../../tmp/workspace/my-app/node_modules/css-loader/lib/css-base.js")(true);
```

This can be repro'd in both Firefox and Chrome. I'm using macOS, Node v8.9.3.

**Comment by nolanlawson** [comment]
Removing `ExtractTextPlugin` and using the dev settings, i.e.:

```
{
  test: /\.css$/,
  use: [
    { loader: 'style-loader' },
    { loader: 'css-loader' }
  ]
}
```

...fixes the issue. I'm not sure why.

**Comment by nolanlawson** [comment]
Ah, I think this may be the issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/456

**Comment by blessingk** [comment]
google maps not displaying in my ionic 3 app

**Comment by blessingk** [comment]
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap f44f4d489902bf3fbd4b:54)
    at Object.297 (onesignal.ts:10)
    at __webpack_require__ (bootstrap f44f4d489902bf3fbd4b:54)
    at webpackJsonpCallback (bootstrap f44f4d489902bf3fbd4b:25)
    at main.js:1
__webpack_require__ @ bootstrap f44f4d489902bf3fbd4b:54
297 @ onesignal.ts:10
__webpack_require__ @ bootstrap f44f4d489902bf3fbd4b:54
webpackJsonpCallback @ bootstrap f44f4d489902bf3fbd4b:25
(anonymous) @ main.js:1

How can I solve that problem I have never changed anything
