### ISSUE TITLE
LICENSE.md is missing

### ISSUE THREAD

**Issue by Razzeee** [sveltejs/sapper-template#28]
Just wanted to say, that it's missing as it's beeing linked to from the README

**Comment by Rich-Harris** [comment]
Ah, good point. I think I removed the license from the repo and package.json because it's not the template's job to decide what license applies to your project, but forgot to remove it from the README, but...

maybe this repo *does* need a license? IANAL, would be glad for any guidance anyone has!

**Comment by LorbusChris** [comment]
If no restrictions apply, maybe this repo ought to decidedly be Public Domain.
CC0 is a License aimed to realise this. To quote from the FAQ: 

>  Think of CC0 as the "no rights reserved" option.

 
https://wiki.creativecommons.org/wiki/Public_domain
https://wiki.creativecommons.org/wiki/CC0_FAQ
