### ISSUE TITLE
"Cannot use namespace 'Preload' as a type" error when typing preload function

### ISSUE THREAD

**Issue by saylerb** [sveltejs/sapper-template#286]
Not sure if this a mistake in the Sapper documentation, or an issue with the template, or something with how TypeScript is configured.  I'm new to TypeScript, so apologies if there's something super obvious that I'm missing here.

Using a fresh install of the sapper template on node 14.15.0 (fermium) and running the TypeScript conversion script, I wanted to test out using the new types for the `preload` function [using the code example in the docs.](https://sapper.svelte.dev/docs#Typing_the_function)

However, using the example from the docs verbatim to add types to the preload in `blog/index.svelte` like this:

```svelte
<script context="module" lang="ts">
  import type { Preload } from "@sapper/common";

  export const preload: Preload = function (this) {
    return this.fetch(`blog.json`)
      .then((r: { json: () => any }) => r.json())
      .then((posts: { slug: string; title: string; html: any }[]) => {
        return { posts };
      });
  };
</script>
```

I get the TypeScript compilation error:

```
~/workspace/sapper-typescript/src/routes/blog/index.svelte:2:3
Hint: 'Preload' is declared but its value is never read. (ts)
<script context="module" lang="ts">
  import type { Preload } from "@sapper/common";


~/workspace/sapper-typescript/src/routes/blog/index.svelte:4:25
Error: Cannot use namespace 'Preload' as a type. (ts)

  export const preload: Preload = function () {
    return this.fetch(`blog.json`)
```

Changing the type import to `import type Common from @sapper/common` fixes the compilation error, and the type of `this` is correctly inferred to be `Common.PreloadContext`:

```svelte
<script context="module" lang="ts">
  import type Common from "@sapper/common";

  export const preload: Common.Preload = function (this) {
    return this.fetch(`blog.json`)
      .then((r: { json: () => any }) => r.json())
      .then((posts: { slug: string; title: string; html: any }[]) => {
        return { posts };
      });
  };
</script>
```

Is the description in the docs wrong? Or am I missing something about TypeScript, where the template's configuration might be wrong? [Here's a link to the test repo I made](https://github.com/saylerb/sapper-typescript)  with both the broken and fixed version as two different commits.

**Comment by PatrickG** [comment]
Why does your function has a `this` argument?

**Comment by saylerb** [comment]
@PatrickG that is the convention for specifying the type of this in TypeScript, as described in the Sapper Docs. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#specifying-the-type-of-this-for-functions

**Comment by PatrickG** [comment]
No, that would be
```js
function (this: Type) {}
```

You did not specify any `Type`.

**Comment by saylerb** [comment]
I believe since I’m providing the return type, TypeScript can infer the type. Are you saying these docs are wrong? https://sapper.svelte.dev/docs#Typing_the_function

**Comment by PatrickG** [comment]
The example should work, whether you specify `this` as an argument or not (although you do not need to specify it).

I just tested it with a fresh install.
It works if you remove the empty `declare module` files in `src/node_modules/@sapper/index.d.ts`. There is already a PR for this issue https://github.com/sveltejs/sapper/pull/1598, but it is not released yet.

**Comment by benmccann** [comment]
Closing this since the fix has already been checked in. Thanks @PatrickG for helping with this!

**Comment by saylerb** [comment]
> The example should work, whether you specify `this` as an argument or not (although you do not need to specify it).
> 
> I just tested it with a fresh install.
> It works if you remove the empty `declare module` lines in `src/node_modules/@sapper/index.d.ts`. There is already a PR that does this ([sveltejs/sapper#1598](https://github.com/sveltejs/sapper/pull/1598)), but it is not released yet.

Ah okay. Thanks for the heads up. I'll be looking out for that next release, I guess.
