### ISSUE TITLE
Service worker warns: No directory provided. Skipping CSS generation

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper-template#298]
Been seeing this warning lately, not sure what has led to it

![Screenshot 2021-01-23 at 2 06 58 pm](https://user-images.githubusercontent.com/2401925/105580500-aded2c00-5d84-11eb-8fbb-2f893ec71b64.png)

Presumably it's something that can be resolved in the rollup config

**Comment by gustavopch** [comment]
Relevant changes that I found:
- https://github.com/sveltejs/sapper/commit/6b143313f422ec670f7cc13ebfc415e2aa1d89e1#diff-571921ec068c7f3022a3c9625c52489e110fd6298971fcf4cadabcea81434a0bR158
- https://github.com/domingues/rollup-plugin-css-chunks/commit/e7483217908a721cef30ae450bf8337043acd90f#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R97

**Comment by yashsamit** [comment]
Any idea how to fix it?

**Comment by jessaleks** [comment]
> Been seeing this warning lately, not sure what has led to it
> 
> ![Screenshot 2021-01-23 at 2 06 58 pm](https://user-images.githubusercontent.com/2401925/105580500-aded2c00-5d84-11eb-8fbb-2f893ec71b64.png)
> 
> Presumably it's something that can be resolved in the rollup config

but where 🤔

**Comment by Pytal** [comment]
I hid the warning message by adding this line into the `onwarn` function of `rollup.config.js`

```js
  (warning.plugin === 'css' && warning.message === 'No directory provided. Skipping CSS generation') ||
```

Full `onwarn` function:

```js
const onwarn = (warning, onwarn) =>
  (warning.code === 'MISSING_EXPORT' && /'preload'/.test(warning.message)) ||
  (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) ||
  (warning.code === 'THIS_IS_UNDEFINED') ||
  (warning.plugin === 'css' && warning.message === 'No directory provided. Skipping CSS generation') ||
  onwarn(warning)
```

**Comment by yashsamit** [comment]
We should identify and remove the problem. This is not a good idea. I think :)

**Comment by didiermunezero** [comment]
> We should identify and remove the problem. This is not a good idea. I think :)

yeah sure.
I would like also to get on that solution on that problem.

**Comment by didiermunezero** [comment]
> > Been seeing this warning lately, not sure what has led to it
> > ![Screenshot 2021-01-23 at 2 06 58 pm](https://user-images.githubusercontent.com/2401925/105580500-aded2c00-5d84-11eb-8fbb-2f893ec71b64.png)
> > Presumably it's something that can be resolved in the rollup config
> 
> but where 🤔

when you are running the sapper project it will

**Comment by rockia** [comment]
I tried to find out the source of this warning and here is what I have found:
When you are using Sapper ^v0.29.0,  you will find 
```         
 if (!generateBundleOpts.dir) {
      this.warn('No directory provided. Skipping CSS generation');
      emitFiles = false;
  }
```

in `node_modules/sapper/dist/create_manifest_data.js`

But sapper doesn't generate this code, it's from the plugin `rollup-plugin-css-chunks` (https://github.com/domingues/rollup-plugin-css-chunks)

**Comment by tri-nga** [comment]
Hi, I just updated Sapper to 0.29.1 and I get this message
No directory provided. Skipping CSS generation, as in the screenshots above.

What's the issue and.. how could I fix that ?

**Comment by babichjacob** [comment]
> 
> 
> Hi, I just updated Sapper to 0.29.1 and I get this message
> No directory provided. Skipping CSS generation, as in the screenshots above.
> 
> What's the issue and.. how could I fix that ?

[Disclaimer: I did not test to see if the latest version of the Sapper template still results in this warning]

If you aren't using the latest version of this Sapper template, then your config hasn't been updated to avoid the warning. So, start over using the latest version of the template or compare its config files and dependencies to yours to see if you can solve the error without starting over.

**Comment by tri-nga** [comment]
> 
> 
> > Hi, I just updated Sapper to 0.29.1 and I get this message
> > No directory provided. Skipping CSS generation, as in the screenshots above.
> > What's the issue and.. how could I fix that ?
> 
> [Disclaimer: I did not test to see if the latest version of the Sapper template still results in this warning]
> 
> If you aren't using the latest version of this Sapper template, then your config hasn't been updated to avoid the warning. So, start over using the latest version of the template or compare its config files and dependencies to yours to see if you can solve the error without starting over.

The message `No directory provided. Skipping CSS generation` showed up after I updated the packages to the latest version available.
I did solve going "back" to the Sapper template packages version.

![working](https://user-images.githubusercontent.com/25151676/115156285-ce770a80-a083-11eb-980c-c9b8f1798381.jpg)

**Comment by silllli** [comment]
A fix has been merged to the master branch, but hasn’t been released yet. To get Sapper with the latest commits (even if not part of a tagged version) you can install it directly from the master branch on GitHub:
`npm install -D sveltejs/sapper#master`
