### ISSUE TITLE
Bug: Rollup plugin-replace: preventAssignment set to "false"

### ISSUE THREAD

**Issue by Christian-Rau** [sveltejs/sapper-template#302]
So today I got this notification, and not sure what to do about it, as I don't see any preventAssignment anywhere.
`
• service worker
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to true.`
• server
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to true.
• client
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to true.
• service worker
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to true.
`

**Comment by Conduitry** [comment]
Transferring this to the sapper-template repo. It probably makes sense to make the `@rollup/plugin-replace` dependency be `^2.4.0` and add this option in `rollup.config.js`.

**Comment by didiermunezero** [comment]
i have the same error and don't know why it is rising. Waiting for solution

**Comment by antony** [comment]
@didiermunezero the solution is posted directly above your comment. Add `preventAssignment: true` to your rollup config.

It's also not an error, it's a warning, and does not stop you continuing unimpeded

**Comment by Christian-Rau** [comment]
I might add: I had trouble running npm, so i rolled back to earlier version. But will apply when upgrading.
Cheers

Hent Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by didiermunezero** [comment]
> @didiermunezero the solution is posted directly above your comment. Add `preventAssignment: true` to your rollup config.
> 
> It's also not an error, it's a warning, and does not stop you continuing unimpeded

Yeah now it works, thank you. But why not make it true by default as you know that it will  give a warning??

**Comment by antony** [comment]
That's quite literally what the warning is telling you, that it will become the default in the next release.

But I'm not sure why you're commenting here - we aren't the authors of rollup-plugin-replace and as such have no part in the decision process.

**Comment by didiermunezero** [comment]
oh that is cool and thanks! @antony

**Comment by guther** [comment]
You need to insert **preventAssignment: true,** in all instances of **replace**, like this:
```
plugins: [
	replace({
		preventAssignment: true,
		'process.browser': true,
		'process.env.NODE_ENV': JSON.stringify(mode)
	}),
```

**Comment by Christian-Rau** [comment]
Closed since it's not a bug, and the sapper template, has been updated.

**Comment by shijiezhou1** [comment]
> You need to insert **preventAssignment: true,** in all instances of **replace**, like this:
> 
> ```
> plugins: [
> 	replace({
> 		preventAssignment: true,
> 		'process.browser': true,
> 		'process.env.NODE_ENV': JSON.stringify(mode)
> 	}),
> ```

Insert and still getting the same warning
