### ISSUE TITLE
Getting started tutorial: Live reload not working

### ISSUE THREAD

**Issue by dok42** [sveltejs/sapper-template#303]
Hello everyone,
I would really like to learn Svelte/Sapper (while waiting for svelte-kit) development but I have this issue actually.
Started the https://sapper.svelte.dev/docs#Getting_started
Done this
```
npx degit "sveltejs/sapper-template#rollup" my-app
# or: npx degit "sveltejs/sapper-template#webpack" my-app
cd my-app
npm install
npm run dev
```
Here's the output:
```
❯ npm run dev

> TODO@0.0.1 dev
> sapper dev

✔ server (1.6s)
✔ client (2.1s)
✔ service worker (190ms)
> Listening on http://localhost:3000
```
Live reloading is not working.

I have searched for existing issues here before posting, but I have not found solutions to the problem.
Could you please provide any help ? 
Thanks 

ps: I'm on Windows 10, and I'm using Ubuntu 20.04 on WSL 2 with no issues so far, except this :)

**Comment by Conduitry** [comment]
If your project lives on your Windows filesystem, WSL fails to report the file change events that Node is listening for. This is a known bug/limitation in WSL 2. If your project lives in the virtual Linux filesystem, the file watching should work fine.

**Comment by Conduitry** [comment]
See also https://github.com/sveltejs/sapper/issues/1150

**Comment by dok42** [comment]
Oh, sorry didn't know about that limitation. My bad.

Thank you very much, will try to move the project directory, or try to avoid wsl if possible. 
Thanks ☺️
