### ISSUE TITLE
Upgrade webpack template to use svelte-loader 3.0.0

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper-template#307]
svelte-loader 3.0.0 fixes numerous issues including HMR support

**Comment by benmccann** [comment]
@non25 maybe you'd like to take a look at this one?

**Comment by non25** [comment]
@benmccann Should we upgrade to webpack 5 as well?
It feels like I should pull `sapper-template-webpack` first and test things out.
Don't know if we still need `webpack-modules` or what about including `webpack-dev-server` and `mini-css-extract-plugin`.
Will need to look into `sapper dev|build|export`. Does it use rollup internally?

**Comment by benmccann** [comment]
I think upgrading webpack would be harder because it would need changes to Sapper, which frankly isn't worth doing with SvelteKit on the way out
