### ISSUE TITLE
(service-worker.js) 'only-if-cached' can be set only with 'same-origin' mode

### ISSUE THREAD

**Issue by thgh** [sveltejs/sapper-template#34]
Chrome devtools on https://svelte.technology/guide
```
The FetchEvent for "https://svelte.technology/guide" resulted in a network error response: the promise was rejected.
Promise.catch (async)
self.addEventListener.event @ service-worker.js:45
service-worker.js:52 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
```

**Comment by poshaughnessy** [comment]
I think @wisdom-yzh [is right](https://github.com/sveltejs/sapper-template/commit/cccd9b98fd9f37a8060168c75d4440f0df4ad704#commitcomment-28155991) and it should be `only-if-cached`, not `only-if-cache` ?

https://github.com/sveltejs/sapper-template/blob/master/app/service-worker.js#L69

**Comment by poshaughnessy** [comment]
I tried changing it to `only-if-cached` to see if that fixed the error for me. It did, but I got a different error now! :D It says "Cannot assign to read only property mode" - pointing to the line where it sets `event.request.mode = "same-origin"`:

![screenshot from 2018-06-29 17-19-52](https://user-images.githubusercontent.com/151207/42103362-bcb3c800-7bc0-11e8-8871-86a1fd3886d8.png)
![screenshot from 2018-06-29 17-19-32](https://user-images.githubusercontent.com/151207/42103366-bf9b38f0-7bc0-11e8-897b-48a58cb27ce2.png)

Sorry for commenting on a closed issue - would you like me to raise a new one?

**Comment by farhaan008** [comment]
Facing the same issue

**Comment by thgh** [comment]
@farhaan008 Here is a solution: https://github.com/sveltejs/sapper-template/blob/7e028c825d46f3e633d0378d4d952c9bb1f61068/app/service-worker.js#L61
