### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by benatkin** [sveltejs/sapper-template#43]
the link to `service-worker.js` at https://github.com/sveltejs/sapper-template#assets is broken, if you click on it you get a 404

**Comment by Rich-Harris** [comment]
this was fixed by https://github.com/sveltejs/sapper-template/commit/7b47c9aab395cba8b8cc09655a28a81ce6ff064d#diff-04c6e90faac2675aa89e2176d2eec7d8 — closing, thanks
