### ISSUE TITLE
Failed build script should not return exit code 0

### ISSUE THREAD

**Issue by hexagon6** [sveltejs/sapper-template#45]
> When running the webpack build running `npm run build` in CI it should be possible to check for failure on the returned exit code.

Expected behaviour:

```
npm run build
# -> some build error happens
Error: Encountered errors while building app
    at /.../node_modules/sapper/cli.js:80:24
echo $?
127
```

What currently happens:
```
npm run build
# -> some build error happens
Error: Encountered errors while building app
    at /.../node_modules/sapper/cli.js:80:24
echo $?
0
```

This would allow detection of broken builds.

**Comment by hexagon6** [comment]
To resolve this we might want to add the `--bail` option to webpack: https://github.com/webpack/webpack/issues/708#issuecomment-71008316

**Comment by hexagon6** [comment]
Alternatively add the webpack-fail-plugin: https://github.com/teamdotjs/v2/pull/190/files

**Comment by Rich-Harris** [comment]
I agree — this is an issue with Sapper itself though rather than this project template, so I'll close this in favour of https://github.com/sveltejs/sapper/issues/208. Thanks
