### ISSUE TITLE
node-fetch not working

### ISSUE THREAD

**Issue by LukasHechenberger** [sveltejs/sapper-template#48]
`PORT` is not defined, in *app/server.js*, therefore `node-fetch` is not working.

This was introduced when switching to polka: https://github.com/sveltejs/sapper-template/commit/6abeb06d7d582b681a36b50d0cf56d93718c7e0a#diff-f53e59f241bb62f0261e245350683e07L11

**Comment by Rich-Harris** [comment]
whoops, that was careless of me! fixed, thanks
