### ISSUE TITLE
How to deploy production to ...

### ISSUE THREAD

**Issue by sgoveia** [sveltejs/sapper-template#51]
@Rich-Harris I am absolutely loving svelte and sapper... But am having trouble understanding how to deploy say to Heroku or AWS. I have built, run, and deployed to "now"(obviously you made that ridiculously simple, thanks..).
Once built is everything I would need in the "app" or "build" dir?
Any advice or pointers would be truly appreciated.
Thanks!!

**Comment by Rich-Harris** [comment]
When you run `sapper build`, Sapper creates a `build` directory containing your app. To run it, you need to do `sapper start` — this sets up all the necessary environment variables and runs `build/server.js`. (Note that you can also do `sapper build custom-dir` and `sapper start custom-dir`, if you want to use a destination other than `build`.)

Your files still exist in the `assets` directory. So to deploy it, you just need to put your `build` and `assets` dir on a server somewhere, `npm install` dependencies, and do `sapper start`. The exact details will differ from one platform to the next, but that's essentially how it works. You don't need do deploy the `app` or `routes` directories. Hope this helps!

**Comment by sgoveia** [comment]
Brilliant! Thank you @Rich-Harris

**Comment by rakia** [comment]
Hi @Rich-Harris,
how about deploying the application in server that does not support node.js? so, I can't use npm install.
I just need a folder like /dist that I just have to copy/paste under an apache server and the app will be deployed automatically.

**Comment by Conduitry** [comment]
@rakia See https://sapper.svelte.technology/guide#exporting

**Comment by rakia** [comment]
thank you @Conduitry, you've answered my question :)

**Comment by tbaums** [comment]
Apologies for commenting on a closed issue, but given the latest updates, what files need to be included to run in Prod? 

The below Dockerfile works great, but produces a  heavy container (39MB). Any suggestions for how to slim this down? I've tried some of the examples on GH to use `COPY --from=0 `, but can't get the right mix of files to get it to deploy (K8s v1.15.X).

```
FROM node:12-alpine
WORKDIR /app
COPY . .
RUN npm install --save
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
```

**Comment by Conduitry** [comment]
To build your app, you need the entire contents of your project as well as all of the dependencies (prod and dev).

To run your app in production, you need `static`, `__sapper__/build`, and all of your prod dependencies.

You can do this with a two-stage Dockerfile. Or you can even use a three-stage Dockerfile if you want your final image to use a base image that doesn't include any package managers.

[The Svelte site](https://github.com/sveltejs/svelte/tree/master/site) has the build itself happen outside of Docker, but then uses a two-stage Docker build, the first of which is used to install npm dependencies, which are then copied into the second, which contains only Node and not npm or Yarn.

**Comment by jcollum-nike** [comment]
@Conduitry  that link above (#exporting) is 404

**Comment by Conduitry** [comment]
It's now https://sapper.svelte.dev/docs#Exporting
