### ISSUE TITLE
Module not found: Can't resolve ....

### ISSUE THREAD

**Issue by renattonl** [sveltejs/sapper-template#52]
I was testing the tutorial to install sapper-template. and when I run npm run dev. I found Module not found: can not solve 'E: proyectossveltemy-app'. The platform that I am using Windows 10.

**Comment by arxpoetica** [comment]
@renattonl this is pretty old and we haven't heard a lot more complaints about it. If you're still having an issue, feel free to reopen, but closing until we hear otherwise.
