### ISSUE TITLE
Template for client-only PWAs ?

### ISSUE THREAD

**Issue by 0gust1** [sveltejs/sapper-template#78]
Hi,

A small open question : I plan to use sapper-template to experiment with client-side only PWAs. First for myself and small projects, but it also could be interesting to other people.

What would be the best way ?
* maintaining a boilerplate as a subset of this template 
  * in this case, is a shell script modifying this template a good idea ? (trimming the serverside/SSR part)
* starting from scratch

It could be saw as a dumb question :) but I find the neat build configuration and tooling packed with the sapper template very useful and well done.

**Comment by frederikhors** [comment]
It would be awesome also for me.

@0gust1, any news?

**Comment by antony** [comment]
Closing in favour of https://github.com/sveltejs/sapper/issues/383
