### ISSUE TITLE
Generate blog posts from Markdown files

### ISSUE THREAD

**Issue by mathiasbynens** [sveltejs/sapper-template#8]
See https://github.com/sveltejs/sapper-template/blob/8687bf3fd81a460739665af5d103faab9c877612/routes/api/blog/_posts.js#L1-L4

Generating blog post HTML from Markdown is common enough that IMHO it makes sense to have this be part of the template. Or maybe there could be a separate `sapper-blog-template` that does this.

**Comment by Rich-Harris** [comment]
I just wanted to avoid adding something like `marked` as a dependency, because then you can't just delete the directory to remove the blog. A separate template is a good idea though! Will probably do that once this one is mature enough to serve as a base.

**Comment by mathiasbynens** [comment]
Looks like `marked` already is a dependency: https://github.com/sveltejs/sapper-template/blob/38898a155de797d54712fa4ec64dec8006ab24ad/package.json#L20 Although it doesn’t seem to be used anywhere.

**Comment by Rich-Harris** [comment]
Good catch, thanks - it's because this repo started life as what eventually became https://hn.svelte.technology, which *does* use marked. Have removed it from package.json
