### ISSUE TITLE
Nicer maintenance of Rollup and Webpack branches

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper-template#93]
See conversation on [this commit](https://github.com/sveltejs/sapper-template/commit/77794e86505c5c75b34ae0dc85bcfb70a32c7538).

I've thrown together a possible initial implementation of this [here](https://git.chor.date/Conduitry/sapper-template-redux). Running `_template/build.sh` creates and force-pushes two branches `rollup` and `webpack` from the current `master` - each with appropriate `package.json` customization and removes the other bundler's config file.

**Comment by thgh** [comment]
Why are there two branches actually? Wouldn't it be easier to maintain if there were two config files and a commandline param to choose which one you want to use?

Then people could try out both or so

**Comment by Conduitry** [comment]
It wouldn't just be a matter of two config files - there would also be differences in the `package.json` dependencies. And also we want people to make changes to their bundler configs in their projects if they need additional plugins or other special handling or whatever. Would the other config still be living in their project all this time, not in sync with the one they're using?

It seems simplest to me to just present two complete and (from the consumer's point of view) independent project starters - which also makes it clearer to them that if they decide to switch bundlers at some point, it's pretty clear that they're going to have some manual migration to do.

If the two branches are automatically built from one common branch, that's not really a maintenance lift for the `sapper-template` repo. And consumers would be getting what they're getting now: two branches, which I think is better for them than a single branch.
