### ISSUE TITLE
preload doesn't work in root page (src/routes/index.html) after visiting a 404

### ISSUE THREAD

**Issue by sgametrio** [sveltejs/sapper-template#94]
## Issue description
Navigating on root page (source at `src/routes/index.html`), which loads data on `preload`, doesn't load data (warning `<Index> was created without expected data property`) only after visiting a 404 page.
## How to reproduce
* Clone [repo](https://github.com/sgametrio/sapper-template)
* `npm install`
* `npm run dev`
* Navigate to `about` route (which return 404) and click on Home to see that data is not loaded.
Try instead to navigate to `about` and then `blog`: data is loaded there even if `blog` and `/index.html` have the same logic.

**Comment by Conduitry** [comment]
Should be fixed by https://github.com/sveltejs/sapper/pull/620.
